---
title: "Tidy evidence syntheses: ‘good enough’ practice and minimum standards in data presentation for maximising legacy, reuse and impact"
description: |
  Good enough practices in data management for systematic maps.
author:
  - name: Neal Haddaway 
    url: 
    affiliation: SEI
    affiliation_url: 
  - name: Matthew Grainger 
    url: 
    affiliation: 
    affiliation_url:
  - name: Ezgi  
    url: 
    affiliation: 
    affiliation_url:
  - name: Charles 
    url: 
    affiliation: R-Ladies
    affiliation_url:
  - name: Andrew  
    url: 
    affiliation: 
    affiliation_url:
  - name: Martin Westgate 
    url: 
    affiliation: 
    affiliation_url:

date: "`r Sys.Date()`"
output: radix::radix_article
bibliography: biblio.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r}
# packages
library(tidyverse)
```


## citation example 
Good enough[@wilson_good_2017]


```{r}
trees <- tibble(
  species_all = c("birch; poplar",
              "oak; birch; pine",
              "",
              "poplar",
              "oak"),
  habitats_all = c(
    "wetlands",
    "forest",
    "forest, wetlands",
    "grasslands",
    "grasslands, forest"
  ),
  id = letters[1:5]
)
```



## unnesting variables

```{r}
trees %>% 
  eviatlas::get_obs("species_all", "species", ";") %>% 
  eviatlas::get_obs("habitats_all", "habitats", ",")


```


## wide data

Suppose different studies observed the presence of different animals. 

```{r}
(trees_wide <- trees %>%
  mutate(
    ants = c(0, 1, 0, 0, 1),
    frogs = c(1, 0, 0, 1, 1),
    wombats = c(0, 0, 0, 0, 1)
  )) 
```

But if we wish to analyse based on the animal observations, we have multiple observations per row. To convert these data into tidy[@tidy-data] format, we need to have one animal observation per row. 

```{r}
(
  trees_wide %>% 
    gather(key = "animal", value = "observed", ants, frogs, wombats)
)
```





